server:
  port: 8080
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          # Git仓库地址
          uri: https://github.com/Linliquan/spring-cloud-config-repo.git
          search-paths: config-repo
          # Git仓库账号
          username: Linliquan
          # Git仓库密码
          password: aa10086LL