server:
  port: 8020
spring:
  application:
    # 指定注册到eureka server上的服务名称
    name: microservice-consumer-movie-feign

eureka:
  client:
    service-url:
      # 指定eureka server通信地址，注意/eureka/小尾巴不能少
      defaultZone: http://localhost:8761/eureka/
  instance:
    # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server
    prefer-ip-address: true

logging:
  level:
    com.itmuch.cloud.study.user.feign.UserFeignClient: debug

# 从Spring Cloud Edgware开始，Feign支持使用属性自定义Feign
feign:
  client:
    config:
      feignName:
        connectTimeout: 2000  # 相当于Request.Options
        readTimeout: 2000     # 相当于Request.Options

management:
  endpoint:
    health:
      # 是否展示健康检查详情
      show-details: always


