server:
  port: 8003
spring:
  application:
    # 注册到Nacos上的服务名称
    name: microservice-provider-user-ali
  jpa:
    # 让hibernate打印执行的SQL
    show-sql: true
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

logging:
  level:
    root: INFO
    # 配置日志级别，让hibernate打印出执行的SQL参数
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
management:
  endpoints:
    web:
      exposure:
        # 暴露metrics端点，如需暴露多个，用,分隔；如需暴露所有端点，用'*'
        include: pause,restart
  endpoint:
    health:
      # 是否展示健康检查详情
      show-details: always

    # 优雅的关掉微服务方式,启用pause端点
    pause:
      enabled: true
    # 启用restart端点，之所以要启用restart端点，是因为pause端点的启用依赖restart端点的启用。
    restart:
      enabled: true

